# remote_theme: pages-themes/tactile@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

title: MTY 5
logo: /assets/images/logo.png
description: "Expansión sensorial: Percibiendo a través de la tecnología"
